# Book settings - ROLLBACK to working version
title: Premium Leaving Certificate Higher Level Maths Notes from TPSA
author: The Problem Solving Association C.L.G.
logo: logo.png

# Execution settings
execute:
  execute_notebooks: force
  hide_input: true

# LaTeX settings
latex:
  latex_documents:
    targetname: book.tex

# Bibliography
bibtex_bibfiles:
  - references.bib

# Repository information
repository:
  url: https://github.com/MichaelAJMitchell/Ecnetica
  path_to_book: ./
  branch: jb

# HTML settings
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  baseurl: ""
  extra_footer: "Copyright-info"
  sidebar:
    maxdepth: 1

# Sphinx configuration
sphinx:
  config:
    html_theme: theme
    html_theme_path: ["."]
    
    html_theme_options:
      navigation_depth: 4
      collapse_navigation: true
    
    html_static_path: ["_static", "theme/static"]
    html_title: "Premium Leaving Certificate Higher Level Maths Notes from TPSA"
    html_short_title: "TPSA Maths Notes"
    templates_path: ["theme/templates"]

# MyST parser settings
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https]
